# This file was generated by GoReleaser. DO NOT EDIT.
class Getgitlabenv < Formula
  desc "Get Gitlab Project env Vars"
  homepage "https://github.com/thobianchi/getGitlabEnv"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thobianchi/gitlabctl/releases/download/1.0.1/getGitlabEnv_Darwin_x86_64.tar.gz"
    sha256 "06dc2c0917fb1e07cd18bd77ef5180b6e039c0e62b254065c8f3d057bc27d61a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/thobianchi/gitlabctl/releases/download/1.0.1/getGitlabEnv_Linux_x86_64.tar.gz"
      sha256 "cba896cd15814ebb0dd293b1a1ae997cda6a484651c6d3ebc7ab052cd9af3b89"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thobianchi/gitlabctl/releases/download/1.0.1/getGitlabEnv_Linux_arm64.tar.gz"
        sha256 "3cefdadf9da69aba0e4442d23cd90a8bda93b0aee3f85d64a07836c6da381f5b"
      else
      end
    end
  end

  def install
    bin.install "getGitlabEnv"
  end

  test do
    system "getGitlabEnv --version"
  end
end
