# This file was generated by GoReleaser. DO NOT EDIT.
class GetGitlabEnv < Formula
  desc "Get Gitlab Project env Vars"
  homepage "https://github.com/thobianchi/getGitlabEnv"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thobianchi/getGitlabEnv/releases/download/1.0.0/getGitlabEnv_Darwin_x86_64.tar.gz"
    sha256 "da2d3c3e366e5809baebf4c18019e40299838fe3e0a6ca701fd317a5b8c139a4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/thobianchi/getGitlabEnv/releases/download/1.0.0/getGitlabEnv_Linux_x86_64.tar.gz"
      sha256 "356362169f43ece71f6230b246b97bfcbeaceec2786a4364cca1606819334f84"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thobianchi/getGitlabEnv/releases/download/1.0.0/getGitlabEnv_Linux_arm64.tar.gz"
        sha256 "73942777ba4bf8ae6733c3094e027381cb25f3e14d99d3cfc6b6eb6b57104feb"
      else
      end
    end
  end

  def install
    bin.install "getGitlabEnv"
  end

  test do
    system "getGitlabEnv --version"
  end
end
