# This file was generated by GoReleaser. DO NOT EDIT.
class Getgitlabenv < Formula
  desc "Get Gitlab Project env Vars"
  homepage "https://github.com/thobianchi/getGitlabEnv"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/thobianchi/getGitlabEnv/releases/download/1.0.1/getGitlabEnv_Darwin_x86_64.tar.gz"
    sha256 "e10f776baa9bbd6d0e042d77b96111b908a7aafde2c666290de44979a5fa1040"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/thobianchi/getGitlabEnv/releases/download/1.0.1/getGitlabEnv_Linux_x86_64.tar.gz"
      sha256 "ae42befeecee2afd26a2ff2370d0880081c715b4b5fc4480fa77971967f8d0e0"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/thobianchi/getGitlabEnv/releases/download/1.0.1/getGitlabEnv_Linux_arm64.tar.gz"
        sha256 "b250e8bf57405a29d1a6386e61ca5c4fced0fbdd99892e6a79d5e92b89f4640d"
      else
      end
    end
  end

  def install
    bin.install "getGitlabEnv"
  end

  test do
    system "getGitlabEnv --version"
  end
end
