# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitlabctl < Formula
  desc "Get Gitlab Project env Vars"
  homepage "https://github.com/thobianchi/gitlabctl"
  version "0.5.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thobianchi/gitlabctl/releases/download/v0.5.0/gitlabctl_Darwin_x86_64.tar.gz"
      sha256 "3e8ca2c2ac20c9702862e7c473c864c1051cc459a4b1ecef871ed7febaaa7a18"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/thobianchi/gitlabctl/releases/download/v0.5.0/gitlabctl_Linux_x86_64.tar.gz"
      sha256 "4934c371484bad6f5bf629de21e672c59a67a6e991a42105fbd8041a5b247857"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thobianchi/gitlabctl/releases/download/v0.5.0/gitlabctl_Linux_arm64.tar.gz"
      sha256 "11353f40d81b1365afc0366ded8288c4ddf347cff7e299100f0adcbf77873f50"
    end
  end

  def install
    bin.install "gitlabctl"
  end

  test do
    system "gitlabctl --version"
  end
end
